"""update relationship table song category : cascade on delete

Revision ID: 794ee6003e15
Revises: 84a3c7278698
Create Date: 2026-01-27 13:10:22.729565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794ee6003e15'
down_revision: Union[str, Sequence[str], None] = '84a3c7278698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song_category',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('song_id', 'category_id')
    )
    op.drop_constraint(op.f('uq_categories_name'), 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_unique_constraint(op.f('uq_categories_name'), 'categories', ['name'])
    op.drop_table('song_category')
    # ### end Alembic commands ###
