"""initial migration: create songs table

Revision ID: e07eafd1e414
Revises: 
Create Date: 2025-12-13 00:59:14.871280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07eafd1e414'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('release', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('composer', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('verse', sa.String(), nullable=True),
    sa.Column('refrain', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_author'), 'songs', ['author'], unique=False)
    op.create_index(op.f('ix_songs_categories'), 'songs', ['categories'], unique=False)
    op.create_index(op.f('ix_songs_composer'), 'songs', ['composer'], unique=False)
    op.create_index(op.f('ix_songs_description'), 'songs', ['description'], unique=False)
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_refrain'), 'songs', ['refrain'], unique=False)
    op.create_index(op.f('ix_songs_release'), 'songs', ['release'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_index(op.f('ix_songs_verse'), 'songs', ['verse'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_verse'), table_name='songs')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_release'), table_name='songs')
    op.drop_index(op.f('ix_songs_refrain'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_description'), table_name='songs')
    op.drop_index(op.f('ix_songs_composer'), table_name='songs')
    op.drop_index(op.f('ix_songs_categories'), table_name='songs')
    op.drop_index(op.f('ix_songs_author'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
